### ISSUE TITLE
Attributes Predefined Selection

### ISSUE THREAD

**Issue by JR-XR** [INCYDE-GmbH/drawio-plugin-attackgraphs#87] opened 2022-10-27 12:04 UTC
Enable feature for Attribute values to not be freely selected inside of a range, but pre select certain values that then can be selected when values are given.

**Comment by tobi18991** [comment] 2022-10-28 07:01
I already created an issue for this. However, thanks for posting this interesting feature request!

Duplicate of #86.

**Closed by tobi18991** 2022-10-28 07:01 UTC
